update

diff --git a/linux/makefile/1/makefile b/linux/makefile/1/makefile
--- a/linux/makefile/1/makefile
+++ b/linux/makefile/1/makefile
@@ -1,11 +1,16 @@
+define commands
+echo "abcdefghijklmnopqrstuvwxyz" > test.c
+@#echo "abcdefghijklmnopqrstuvwxyz" > /etc/null		#Error
+grep -q "abc" test.c
+echo $$?
+grep -q "aaa" test.c; \
+if test $$? -eq 0; \
+then echo "="; \
+else echo "!="; \
+fi
+endef
+
 all:
-	echo "abcdefghijklmnopqrstuvwxyz" > test.c
-	@#echo "abcdefghijklmnopqrstuvwxyz" > /etc/null		#Error
-	grep -q "abc" test.c
-	echo $$?
-	grep -q "aaa" test.c; \
-	if test $$? -eq 0; \
-	then echo "="; \
-	else echo "!="; \
-	fi
+	$(commands)
+
 
